### PR TITLE
APPS-580 Commit PITR Helm charts to the public repo

### PR DESCRIPTION
**Pull request by davi17g**
I left the Description section empty, but we need to discuss what info should be provided there.

### CODE REVIEW

**Review by hev — CHANGES_REQUESTED** [review]
I say we avoid duplicating install instructions and consolidate to all docs living at https://aerospike.github.io/point-in-time-recovery

**Review by hev — APPROVED** [review]
Also, let's not use the name "enterprise backup"

**Review by hev — CHANGES_REQUESTED** [review]
I tried to make some changes but wasn't able to push them. Let's do the following. 

* reduce README to a simple description pointing to https://aerospike.github.io/point-in-time-recovery and also keep the configuration table
* move the folder to aerospike-point-in-time-recovery

**Review by hev — APPROVED** [review]
LGTM

**Review by reugn — COMMENTED** [review]
@davi17g Update the Helm charts list in the readme.

**Pull request merged**
